version: "3"

services:
  phoenix:
    image: phoenix/scholarr:latest
 #   build: .
    ports:
      - "4000:4000"
    volumes:
      - /media/cursos:/media
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - DATABASE_URL=ecto://postgres:postgres@db/postgres
      - SECRET_KEY_BASE=a6UIvdUMRW1p+Nwq0WqUwFKtFipUiAAc+UDP/i/ecGAoFukUDFd7giSQZBRJ8W3J
    depends_on:
      - db
  db:
    image: postgres:10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=scholarr
